<a href="https://colab.research.google.com/github/apolloadeniran/Assignment/blob/main/Adeniran_Lateef_Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix problem is calculated manually

In [7]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_array = a_ndarray * b_ndarray
print(c_array)


[[  0   4   3]
 [  0 -10 -48]
 [ 14  72   9]]


###Problem 2. Calculation by NumPy function

Using matmul()

In [8]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.matmul(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Using dot

In [9]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
ab_ndarray = np.dot(a_ndarray, b_ndarray)
print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


###Problem 3. Implementation of calculation of a certain element

1. Multiply the (0,0) element $a_{0, 0}$ of matrix A with the (0,0) element $b_{0, 0}$ of matrix B

In [10]:
ab = (a_ndarray[0][0]*b_ndarray[0][0])
ab

0

2. Multiply the (0,1) element $a_{0, 1}$ of matrix A with the (1,0) element $b_{1, 0}$ of matrix B

In [11]:
ab = (a_ndarray[0][1]*b_ndarray[1][0])
ab

0

3. Multiply the (0,2) element $a_{0, 2}$ of matrix A with the (2,0) element $b_{2, 0}$ of matrix B

In [12]:
ab = (a_ndarray[0][2]*b_ndarray[2][0])
ab

6

3. Add all those values together

In [13]:
sum_ab = (a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0])
sum_ab

6

###Problem 4. Creating a function that performs matrix multiplication

In [17]:
def product_of_matrix(a,b):
    matrix_ab = np.empty([3,3])
    for row1 in range(a.shape[0]):
        for column1 in range(b.shape[1]):
            matrix_ab[row1][column1] = sum(a[row1, 1]*b[:, column1])
    return matrix_ab
print(product_of_matrix(a_ndarray, b_ndarray))



[[  4.  26. -16.]
 [-10. -65.  40.]
 [ 16. 104. -64.]]


###Problem 5. Judge the input whose calculation is not defined

In [25]:

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
if d_ndarray.shape[0] == d_ndarray.shape[1]:
   print(product_of_matrix(a_ndarray, b_ndarray))
else:
    print("matrix are not aligned")

matrix are not aligned


###Problem 6. Transposition

In [26]:
z = d_ndarray.T
print(product_of_matrix(z, e_ndarray))


[[-12.  12.  44.]
 [ 15. -15. -55.]
 [-18.  18.  66.]]
